#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	// fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	u32 max_mask = 0;

	rt_entry_t *entry = NULL;
	rt_entry_t *result = NULL;

	list_for_each_entry(entry, &rtable, list) {
		if ((dst & entry->mask) == (entry->dest & entry->mask)) {
			if (entry->mask >= max_mask) {
				max_mask = entry->mask;
				result = entry;
			}
		}
	}
	return result;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// fprintf(stderr, "TODO: send ip packet.\n");

	struct ether_header* eh = (struct ether_header*)packet;

	struct iphdr* iph = (struct iphdr*)(packet + sizeof(struct ether_header));

	u32 daddr = ntohl(iph->daddr);

	pthread_mutex_lock(&rtable_mutex);
	rt_entry_t* d_entry = longest_prefix_match(daddr);

	if (!d_entry) {
		// No such route found in routing table
		free(packet);
		pthread_mutex_unlock(&rtable_mutex);
		return;
	}

	u32 next_hop = d_entry->gw ? d_entry->gw : daddr;

	memcpy(eh->ether_dhost, d_entry->iface->mac, ETH_ALEN); // set dest addr in Ethernet header
	eh->ether_type = htons(ETH_P_IP);


	iface_send_packet_by_arp(d_entry->iface, next_hop, packet, len);
	pthread_mutex_unlock(&rtable_mutex);
	return;
}
